{{- if .Values.defaultImagePullSecret.enabled -}}
apiVersion: v1
metadata:
  name: {{ include "inspector.defaultImagePullSecret" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
kind: Secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "inspector.defaultImagePullSecret.dockerconfigjson" . }}
{{- end -}}